leftnav:
- identifier: d4bebeb8-6ec3-7067-9595-0552bd88273b
  name: Syllabus
  url: /pages/syllabus
  weight: 10
- identifier: fe64ffa9-621d-8eb6-a8ab-635c42e43233
  name: Calendar
  url: /pages/calendar
  weight: 20
- identifier: 24305b59-29f4-033f-a26a-3009c8319163
  name: Readings
  url: /pages/readings
  weight: 30
- identifier: 55878743-c1ec-be5d-8d5a-c8eb585e20d3
  name: Lecture Notes
  url: /pages/lecture-notes
  weight: 40
- identifier: 46f448cb-c5d5-f10d-68ed-b62fbaaf26e5
  name: Assignments
  url: /pages/assignments
  weight: 50
- identifier: 39c57347-86fd-2b8c-8619-85bb15e6a356
  name: Exams
  url: /pages/exams
  weight: 60
- identifier: e0e5e093-c59d-575a-ab8c-2dac69136760
  name: Projects
  url: /pages/projects
  weight: 70
- identifier: 147a28ca-b914-07ea-e011-25a5eb8c674e
  name: Study Materials
  url: /pages/study-materials
  weight: 80
